// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_commerce.Data.Context;

#nullable disable

namespace e_commerce.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20230702170122_Test1")]
    partial class Test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("e_commerce.Models.asbstractClasses.AbstractProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("product_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("product_type").HasValue("AbstractProduct");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("e_commerce.Models.classes.Processor", b =>
                {
                    b.HasBaseType("e_commerce.Models.asbstractClasses.AbstractProduct");

                    b.Property<float>("BaseClockSpeed")
                        .HasColumnType("real");

                    b.Property<float>("BoostClockSpeed")
                        .HasColumnType("real");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Processors");
                });

            modelBuilder.Entity("e_commerce.Models.classes.VideoCard", b =>
                {
                    b.HasBaseType("e_commerce.Models.asbstractClasses.AbstractProduct");

                    b.Property<string>("Assembler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemoryInGB")
                        .HasColumnType("int");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("int");

                    b.ToTable("Products", t =>
                        {
                            t.Property("YearOfRelease")
                                .HasColumnName("VideoCard_YearOfRelease");
                        });

                    b.HasDiscriminator().HasValue("VideoCards");
                });
#pragma warning restore 612, 618
        }
    }
}
